### ISSUE TITLE
Add support for Nodebb default quote system

### ISSUE THREAD

**Issue by Pilvinen** [NodeBB/nodebb-plugin-composer-redactor#15]
When you press "quote" to reply to a thread it should have Redactor support so that you don't have to manually select the quote and click format -> quote to turn it into the actual quoting format.

**Comment by drewdotpro** [comment]
Ah yeah the current behaviour is pretty gross for that. Thanks for flagging it up.

**Comment by drewdotpro** [comment]
@julianlam I know what I need to do here, instead of taking the content and wrapping it in markdown quote I need to take it and wrap it in a <blockquote> tag. But where on earth does that happen? And how do I override it?

**Comment by drewdotpro** [comment]
Ok so it looks like it's done here
https://github.com/NodeBB/NodeBB/blob/305c54a727edbb861ef67642f8bbc77ecdd2c027/public/src/client/topic/postTools.js#L144

and here
https://github.com/NodeBB/NodeBB/blob/305c54a727edbb861ef67642f8bbc77ecdd2c027/public/src/client/topic/postTools.js#L182

How does a plugin go about overriding this?

**Comment by drewdotpro** [comment]
In disucssion here:
https://community.nodebb.org/topic/6341/override-the-default-reply-behaviour

**Comment by drewdotpro** [comment]
https://github.com/NodeBB/NodeBB/issues/3468

**Comment by psychobunny** [comment]
@barisusakli added support for this in btw, just in case you didn't notice :)

**Comment by drewdotpro** [comment]
Thanks, yes I had a look but couldn't figure out how to get this going:
https://community.nodebb.org/topic/6093/official-redactor-composer-now-available-in-0-7-1/61

**Comment by drewdotpro** [comment]
Fixed in 1.1.1 =)
