### ISSUE TITLE
Composer transform makes icons to appear blurry

### ISSUE THREAD

**Issue by exomarty** [NodeBB/nodebb-plugin-composer-redactor#17]
this class from nodebb composer that transform composer size makes icons to apper blurry

![captura de pantalla 2015-09-07 a las 3 19 45](https://cloud.githubusercontent.com/assets/10746278/9707670/7f3af2b2-550f-11e5-867e-18e289638eb0.png)

blurry
![captura de pantalla 2015-09-07 a las 3 20 20](https://cloud.githubusercontent.com/assets/10746278/9707675/9ed6119c-550f-11e5-9a67-e42d190a023a.png)

non blurry
![captura de pantalla 2015-09-07 a las 3 20 34](https://cloud.githubusercontent.com/assets/10746278/9707681/ac7b613a-550f-11e5-8439-ef05ee0ed8a2.png)

**Comment by drewdotpro** [comment]
I think the transform applied here is done by NodeBB. I can't recreate the blurry effect on Firefox or Chrome though.

**Comment by exomarty** [comment]
Its present on all browsers for me. 
Just disable the transform css and you will see the difference. 
And yes. Its done by nodebb but it doesnt seems to happen on composer default

**Comment by exomarty** [comment]
seems solved in last version

**Comment by drewdotpro** [comment]
Closing then
