### ISSUE TITLE
enable upload files, images?

### ISSUE THREAD

**Issue by lslzl3000** [NodeBB/nodebb-plugin-composer-redactor#2]
How to enable upload files in the composer?

**Comment by julianlam** [comment]
Hi there @lslzl3000, this is not implemented yet, unfortunately. If you want to enable file uploads, you'll have to switch back to the regular composer _for the time being_.

I may look into doing this today.

**Comment by lslzl3000** [comment]
Thanks for your reply!
I'm new to this community, great platform. I'll study its structure and try to make some contribution to nodebb.
I have noticed that you are(are you?) the main developer in this community, and I'm going to develop a forum for a startup team, many changes & functions shall be made. Can I ask you for help if any problems or questions?

**Comment by julianlam** [comment]
Your best bet is to start threads in [our community forum](https://community.nodebb.org). More answers there :smile:

**Comment by julian9444** [comment]
The plugin is very well , but it lacks the icon to upload a picture

**Comment by PAEz** [comment]
Ive decided Id like a WYSIWYG editor, but no uploads (want the to imgur stuff later) is a bummer so I had a look.
The way things are it aint good.
Redactor looks real cool, but isnt very flexible.
Redactor needs a way to add headers as its seems you need to add this header...
`'x-csrf-token': csrf.get()`
You also need to setup the image upload settings like so...

```
$.Redactor.opts.imageUpload='/api/post/upload';
$.Redactor.opts.imageUploadParam='files[]';
```

..so that it sends to the right place with the right name.  I just put this in my dropbox button plugin so far, needs a better place.
Last prob is that redactor expects the file to return an object with the link to the file, like thus...

```
{ "filelink": "/images/img.jpg" }
```

...whereas nodebb is returning....

```
[{"url":"/uploads/files/1439728017665-frame.png","name":"frame.png"}]
```

...the array doesnt matter as redactor removes the [] and then parses the result (which seems stupid to me, its not safe.  If there is any array with two or more items it will fail. Wouldnt it be better to add and array if there isnt one and only take the first item???) .  The problem is redactor wants `filelink`, so I just added some code to redactor to copy it to filelink if url is there.

With those changes Ive been able to get redactor to upload to the public/uploads directory.

So Redactor needs...
A way to set headers.
A way to change the variable it looks for from the return.

I changed Redactors upload.sendData function to this....

```
            sendData: function(formData, e)
                {
                    // append hidden fields
                    if (this.upload.type == 'image')
                    {
                        formData = this.upload.getHiddenFields(this.opts.uploadImageFields, formData);
                        formData = this.upload.getHiddenFields(this.upload.imageFields, formData);
                    }
                    else
                    {
                        formData = this.upload.getHiddenFields(this.opts.uploadFileFields, formData);
                        formData = this.upload.getHiddenFields(this.upload.fileFields, formData);
                    }

                    var xhr = new XMLHttpRequest();
                    xhr.open('POST', this.upload.url);
                    xhr.setRequestHeader("X-Requested-With", "XMLHttpRequest");

///PAEz
    var opts=this.opts;
if(opts.imageUploadHeaders){
    var keys = Object.keys(opts.imageUploadHeaders);

    keys.forEach(function(key){
        xhr.setRequestHeader(key, opts.imageUploadHeaders[key]);
    })
}
///
                    // complete
                    xhr.onreadystatechange = $.proxy(function()
                    {
                        if (xhr.readyState == 4)
                        {
                            var data = xhr.responseText;

                            data = data.replace(/^\[/, '');
                            data = data.replace(/\]$/, '');

                            var json;
                            try
                            {
                                json = (typeof data === 'string' ? $.parseJSON(data) : data);
                            }
                            catch(err)
                            {
                                json = {
                                    error: true
                                };
                            }


                            this.progress.hide();

                            if (!this.upload.direct)
                            {
                                this.upload.$droparea.removeClass('drag-drop');
                            }
///PAEz
if(opts.imageUploadKey)json.filelink=json[opts.imageUploadKey];
///
                            this.upload.callback(json, this.upload.direct, e);
                        }
                    }, this);


                    /*
                    xhr.upload.onprogress = $.proxy(function(e)
                    {
                        if (e.lengthComputable)
                        {
                            var complete = (e.loaded / e.total * 100 | 0);
                            //progress.value = progress.innerHTML = complete;
                        }

                    }, this);
                    */


                    xhr.send(formData);
                },
```

...and then somewhere before redactor gets initd (I did it in my button extension) add this....

```
            $.Redactor.opts.imageUpload='/api/post/upload';
            $.Redactor.opts.imageUploadParam='files[]';
            var csrf=require("csrf");
            $.Redactor.opts.imageUploadHeaders={'x-csrf-token': csrf.get()};.
            $.Redactor.opts.imageUploadKey='url';
```

So please pass this info along to who ever owns the license (non OS, bleh!) and see if we can get something going.

**Comment by drewdotpro** [comment]
@PAEz thanks so much for including this.
I'm going to contact imperavi about it and see if it's something they'd consider including.

**Comment by PAEz** [comment]
@drewdotpro Sweet!
The way the keys handled should definitely be different, should be handled where ever that key is actually used but couldnt be bothered looking for it ;) (it should just change the key it references rather than copy it to the one it usually expects).  Other than that I cant see why itd be bad/unsafe?

**Comment by drewdotpro** [comment]
I'm going to pick this up over the weekend. As Imperavi essentially only want to fix bugs I think the smartest plan to be able to keep their code in line with ours is for me to create a branch for it where I put only their changes and then use a rebase approach to be able to maintain our changes against theirs.

**Comment by drewdotpro** [comment]
I think I also need to look into how to configure this to work with imgur (for bedroom coder l33ts) and S3 (for professional coder l33ts).

**Comment by yariplus** [comment]
Hey @drewdotpro, I've been messing around with this for a while.

In the client script, you can actually just override the function sendData. It might be a better option since I doubt we'll be making a ton of changes.

I tested it and it worked out-of-the-box with the imgur and s3 plugins.

**Comment by drewdotpro** [comment]
Hmm, the downside there is if they make changes to their sendData function we'd not get them. It's certainly easier and less messy than doing rebases. Tough call. I'll mull it over while I'm at the pub.

**Comment by drewdotpro** [comment]
I am taking the rebase approach for maintaining this repo.
Image uploads supported in 1.0.12

**Comment by yariplus** [comment]
Nice, but any idea why this isn't working with Imgur for me? It's puking all over the screen about eventemitters reaching the max.

**Comment by barisusakli** [comment]
Can you post stack trace, nodebb githash, imgur plugin version etc.

**Comment by yariplus** [comment]
e0101fcd248fb5ae7a848a8e452b4dd1332de094

Imgur version 1.0.6

```
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at ReadStream.EventEmitter.addListener (events.js:160:15)
    at Function.DelayedStream.create (/home/yari/nodebb/node_modules/request/node_modules/combined-stream/node_modules/delayed-stream/lib/delayed_stream.js:33:10)
    at FormData.CombinedStream.append (/home/yari/nodebb/node_modules/request/node_modules/combined-stream/lib/combined_stream.js:43:37)
    at FormData.append (/home/yari/nodebb/node_modules/request/node_modules/form-data/lib/form_data.js:43:3)
    at appendFormValue (/home/yari/nodebb/node_modules/request/request.js:342:21)
    at Request.init (/home/yari/nodebb/node_modules/request/request.js:353:11)
    at new Request (/home/yari/nodebb/node_modules/request/request.js:139:8)
    at request (/home/yari/nodebb/node_modules/request/index.js:55:10)
    at Function.post (/home/yari/nodebb/node_modules/request/index.js:63:12)
    at doUpload (/home/yari/nodebb/node_modules/nodebb-plugin-imgur/index.js:183:12)
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at ReadStream.EventEmitter.addListener (events.js:160:15)
    at FormData.CombinedStream.append (/home/yari/nodebb/node_modules/request/node_modules/combined-stream/lib/combined_stream.js:47:14)
    at FormData.append (/home/yari/nodebb/node_modules/request/node_modules/form-data/lib/form_data.js:43:3)
    at appendFormValue (/home/yari/nodebb/node_modules/request/request.js:342:21)
    at Request.init (/home/yari/nodebb/node_modules/request/request.js:353:11)
    at new Request (/home/yari/nodebb/node_modules/request/request.js:139:8)
    at request (/home/yari/nodebb/node_modules/request/index.js:55:10)
    at Function.post (/home/yari/nodebb/node_modules/request/index.js:63:12)
    at doUpload (/home/yari/nodebb/node_modules/nodebb-plugin-imgur/index.js:183:12)
    at uploadToImgur (/home/yari/nodebb/node_modules/nodebb-plugin-imgur/index.js:210:4)
30/8 19:03 [19296] - error: undefined
undefined
30/8 19:03 [19296] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
30/8 19:03 [19296] - info: [app] Database connection closed.
30/8 19:03 [19296] - info: [app] Web server closed to connections.
30/8 19:03 [19296] - info: [app] Shutdown complete.
[cluster] Child Process (19296) has exited (code: 1, signal: null)
[cluster] Spinning up another process...
```

**Comment by barisusakli** [comment]
Did you setup an imgur app with key/secret and click authorize in the plugin page?

**Comment by yariplus** [comment]
Hmm, I did, but maybe it got erased when I updated it last, one sec.

Nope, everything was still setup. Did a re-authorize just to make sure and still persists.

**Comment by barisusakli** [comment]
Nvm I reproduced working on a fix.

**Comment by yariplus** [comment]
:+1:

**Comment by barisusakli** [comment]
published nodebb-plugin-imgur 1.0.7

**Comment by yariplus** [comment]
`30/8 21:55 [23101] - error: [plugins] filter:uploadImage,  [[error:invalid-refresh-token]]`

Any idea?

**Comment by barisusakli** [comment]
That happens when the imgur app isn't authorized
