### ISSUE TITLE
Firefox issues - highlighting, editing text

### ISSUE THREAD

**Issue by Errapolis** [NodeBB/nodebb-plugin-composer-redactor#22]
Using Firefox on Win7, I found the following issues:

 Highlighting text (either by double-clicking a word or click-and-drag highlighting) doesn't work at all, unless done in HTML mode.
 Highlighting text in HTML mode, then clicking "link" to add a hyperlink: the "selected" text isn't added to the "Text" box in the "Insert link" popup, and must be retyped.

No similar problems in Chrome.

NodeBB version 0.8.1

**Comment by drewdotpro** [comment]
Confirmed as an issue present in NodeBB Redactor, but not Redactor editor on official site. Can recreate. No idea what the cause is yet.

**Comment by drewdotpro** [comment]
This is caused by .composer having
-moz-user-select: none

@julianlam I can override this, but wondering why it's there at all?

**Comment by Errapolis** [comment]
Excellent, working perfectly in Firefox now.
