### ISSUE TITLE
White background

### ISSUE THREAD

**Issue by ricoud** [NodeBB/nodebb-plugin-composer-redactor#26]
When using bootswatch dark skin (Cyborg, Darkly, etc) you can't see Heading (white text on white background).

**Comment by drewdotpro** [comment]
I didn't realise people were using skins any more. I think that feature's heading to pasture.
Will look into this.

**Comment by shaaati** [comment]
This a really annoying bug. A custom dark skin also turns my normal text to a light grey (visible, but quite stressful to read) and hyperlinks are white on white and thus invisible.

**Comment by psychobunny** [comment]
This seems to be fixed now
