### ISSUE TITLE
plugin poll not available

### ISSUE THREAD

**Issue by Pappmann** [NodeBB/nodebb-plugin-composer-redactor#36]
nodebb-plugin-poll is not available

**Comment by julianlam** [comment]
This is a separate plugin for NodeBB :smile:, what is your query?

**Comment by Pappmann** [comment]
i know, poll is not dispayed in composer

for example, composer-default:
![image](https://cloud.githubusercontent.com/assets/16403474/12156072/02a10ce0-b4c9-11e5-90de-e9f41652e819.png)

**Comment by yariplus** [comment]
Soon :tm:
