### ISSUE TITLE
No autocomplete of emoji

### ISSUE THREAD

**Issue by deiden26** [NodeBB/nodebb-plugin-composer-redactor#53]

**Comment by binoalien** [comment]
https://github.com/binoalien/nodebb-plugin-composer-redactor

**Comment by julianlam** [comment]
@binoalien Please open a pull request for it 😄 

https://github.com/binoalien/nodebb-plugin-composer-redactor/pull/new/master

**Comment by binoalien** [comment]
@julianlam i have do this, now

**Comment by julianlam** [comment]
TYVM 😄

**Comment by julianlam** [comment]
Seems okay now.
