### ISSUE TITLE
Displays double submit dropdown buttons when used with the Question and Answer plugin

### ISSUE THREAD

**Issue by deiden26** [NodeBB/nodebb-plugin-composer-redactor#54]
Default Composer
![screen shot 2016-08-22 at 11 43 20 am](https://cloud.githubusercontent.com/assets/2993523/17867044/ababe376-685d-11e6-90aa-0fff7adfc27a.png)

Redactor
![screen shot 2016-08-22 at 11 41 47 am](https://cloud.githubusercontent.com/assets/2993523/17867050/b40c3066-685d-11e6-896a-e20ded9e4901.png)

**Comment by psychobunny** [comment]
This should be fixed as of latest Q&A plugin, though if not please reopen there instead :)
