### ISSUE TITLE
Integrate Redactor II

### ISSUE THREAD

**Issue by julianlam** [NodeBB/nodebb-plugin-composer-redactor#59]
We've received a new Redactor version from @drewdotpro, and it needs to be integrated properly into this plugin.

So far there are some breaking changes, including (but not limited to):

* No more .setAwesome(), so all plugins with Redactor integration need fixing (/cc @yariplus )
* Changes in API as per their new doc (things like focus, insertNode, etc...)
* Emoji plugin not at all compatible anymore, so removed (/cc @exomarty )

The 2.0 branch is currently unusable, and is located in the `redactor-ii` branch.

**Comment by julianlam** [comment]
Instead of `.setAwesome`, I got it working for topic thumbs with this line: https://github.com/NodeBB-Community/nodebb-plugin-composer-redactor/blob/redactor-ii/static/lib/redactor.core.js#L77

Though we could consider using the Iconic plugin by Redactor: https://imperavi.com/redactor/examples/buttons-default-icons/

Though... it didn't seem to work when I added it, so perhaps there are some changes to be made. I've removed it from the branch for now.

**Comment by julianlam** [comment]
Also @exomarty your custom emoji **cannot** be added to this repo. They show up on everybody's redactor installation, which is bad. Correct course would be to fire off a plugin hook so other plugins (namely, your theme) can define their own emoji.

... also `psyduck.gif`? Let's not get sued by Nintendo 😄

**Comment by exomarty** [comment]
My custom emoji plugin was not finished. Those .gif were only as example
Main icons were the emojione pack

It shoudnt be hard to update it to make it work with new version
This was the main plugin https://github.com/Nevon/redactor-emoticons

Also very happy to see redactor updated

**Comment by julianlam** [comment]
Good to know @exomarty -- would it be possible to integrate with emoji-extended instead of using the redactor plugin?

**Comment by exomarty** [comment]
I guess emoji extended already have emojione pack
https://github.com/NodeBB-Community/nodebb-plugin-emoji-one

**Comment by julianlam** [comment]
This is done now.
