### ISSUE TITLE
Add link button doesn't do anything

### ISSUE THREAD

**Issue by Pilvinen** [NodeBB/nodebb-plugin-composer-redactor#61]
Redactor 1.4.15
Nodebb 1.4.1

**Comment by Pilvinen** [comment]
Oh. And the same goes with "formatting", "table" and "alignment" buttons.

**Comment by paviro** [comment]
It does work for me but the added Links are not clickable anywhere but in the editor 🤷‍♂️

**Comment by julianlam** [comment]
Works in latest
