### ISSUE TITLE
Tables / Links / Lists not shown

### ISSUE THREAD

**Issue by paviro** [NodeBB/nodebb-plugin-composer-redactor#64]
Seems like none of the features I tried in the editor are actually showing up in the saved post. I created a table (looked perfectly in the editor) and in the post I just had the text. Same with links none are clickable. Lists also end up as text only.

**Comment by psychobunny** [comment]
Hello, have you disabled both markdown and default composer plugins?

**Comment by paviro** [comment]
Thanks for your quick reply! :)
Markdown is enabled but the HTML function is turned on as stated in the README. Default composer is disabled. I have SanitizeHTML installed but the used tags are allowed.

**Comment by julianlam** [comment]
Please let me know if this still reproduces on latest Redactor, thanks.
