### ISSUE TITLE
Redactor-composer seems to have changed 

### ISSUE THREAD

**Issue by JonathanWatkins** [NodeBB/nodebb-plugin-composer-redactor#66]
I have just updated to 1.4.2. Any ideas why my redactor composer looks like this now?
<img width="1403" alt="screen shot 2017-01-19 at 19 18 11" src="https://cloud.githubusercontent.com/assets/1997938/22121517/58c5ed10-de7c-11e6-9d71-fa1ac8dd2971.png">

**Comment by julianlam** [comment]
Doesn't look like anything to me...

😛  Seriously though, that looks ok?

**Comment by pitaj** [comment]
Are you referring to the "Replying to ..." text missing, or what?

**Comment by JonathanWatkins** [comment]
Sorry I wasn't very clear. It used to look like this
<img width="894" alt="screen shot 2017-01-19 at 19 34 48" src="https://cloud.githubusercontent.com/assets/1997938/22122098/7ac79e20-de7e-11e6-919a-3c2e935b9ea1.png">

**Comment by JonathanWatkins** [comment]
I can't manually edit html for example

**Comment by julianlam** [comment]
Yes, I believe the tagging is at the bottom now, and the toolbar options have changed as we've updated to the newest version of Redactor, which does not have the same plugins as the old.

**Comment by JonathanWatkins** [comment]
Sorry to post here again but I have been trying to uninstall and install the composers and now I see this on the console.

nodebb.min.js?2b902572-9711-435a-91d8-7c8e4ec8c093:20 Uncaught TypeError: Cannot read property 'newTopic' of undefined
    at nodebb.min.js?2b902572-9711-435a-91d8-7c8e4ec8c093:20
    at dispatch (nodebb.min.js?2b902572-9711-435a-91d8-7c8e4ec8c093:2)
    at m.handle (nodebb.min.js?2b902572-9711-435a-91d8-7c8e4ec8c093:2)
    at Object.trigger (nodebb.min.js?2b902572-9711-435a-91d8-7c8e4ec8c093:3)
    at nodebb.min.js?2b902572-9711-435a-91d8-7c8e4ec8c093:3
    at Function.each (nodebb.min.js?2b902572-9711-435a-91d8-7c8e4ec8c093:1)
    at v.fn.init.each (nodebb.min.js?2b902572-9711-435a-91d8-7c8e4ec8c093:1)
    at v.fn.init.trigger (nodebb.min.js?2b902572-9711-435a-91d8-7c8e4ec8c093:3)
    at Object.app.newTopic (nodebb.min.js?2b902572-9711-435a-91d8-7c8e4ec8c093:11)
    at HTMLButtonElement.<anonymous> (nodebb.min.js?2b902572-9711-435a-91d8-7c8e4ec8c093:10)

I wonder if this all related to https://github.com/NodeBB/NodeBB/issues/5381 which I have just posted.

I seem to be in a bit of a mess.

**Comment by JonathanWatkins** [comment]
If I run ./nodebb dev I see these warnings

19/1 20:04:16 [24049] - warn: [plugins/load] File not found: /home/ec2-user/nodebb/node_modules/nodebb-plugin-composer-default/static/lib/composer.js (Ignoring)
19/1 20:04:16 [24049] - warn: [plugins/load] File not found: /home/ec2-user/nodebb/node_modules/nodebb-plugin-composer-default/static/lib/composer/autocomplete.js (Ignoring)
19/1 20:04:16 [24049] - warn: [plugins/load] File not found: /home/ec2-user/nodebb/node_modules/nodebb-plugin-composer-default/static/lib/composer/categoryList.js (Ignoring)
19/1 20:04:16 [24049] - warn: [plugins/load] File not found: /home/ec2-user/nodebb/node_modules/nodebb-plugin-composer-default/static/lib/composer/controls.js (Ignoring)
19/1 20:04:16 [24049] - warn: [plugins/load] File not found: /home/ec2-user/nodebb/node_modules/nodebb-plugin-composer-default/static/lib/composer/drafts.js (Ignoring)
19/1 20:04:16 [24049] - warn: [plugins/load] File not found: /home/ec2-user/nodebb/node_modules/nodebb-plugin-composer-default/static/lib/composer/formatting.js (Ignoring)
19/1 20:04:16 [24049] - warn: [plugins/load] File not found: /home/ec2-user/nodebb/node_modules/nodebb-plugin-composer-default/static/lib/composer/preview.js (Ignoring)
19/1 20:04:16 [24049] - warn: [plugins/load] File not found: /home/ec2-user/nodebb/node_modules/nodebb-plugin-composer-default/static/lib/composer/resize.js (Ignoring)
19/1 20:04:16 [24049] - warn: [plugins/load] File not found: /home/ec2-user/nodebb/node_modules/nodebb-plugin-composer-default/static/lib/composer/tags.js (Ignoring)
19/1 20:04:16 [24049] - warn: [plugins/load] File not found: /home/ec2-user/nodebb/node_modules/nodebb-plugin-composer-default/static/lib/composer/uploads.js (Ignoring)

**Comment by JonathanWatkins** [comment]
Just rand ./nodebb upgrade again. That seems to have helped with the file not founds an newTopic undefined.

I'll look into the changes to redactor. I may use the old version since I can't see and edit html button which is useful.

Thanks

**Comment by JonathanWatkins** [comment]
I see what has happened with redactor. I need to add the source code plugin to redactor to get the html edit back. Any ideas how to do this in NodeBB?

https://imperavi.com/redactor/plugins/source/

**Comment by JonathanWatkins** [comment]
Never mind. It says in the post I just sent you. :)

**Comment by JonathanWatkins** [comment]
<script src="/js/redactor/plugins/source.js"></script>

    <script type="text/javascript">
    $(function()
    {
        $('#redactor').redactor({
            plugins: ['source']
        });
    });

**Comment by exomarty** [comment]
i bet that new text icons would be horrible on mobile
it is possible to get back to simple icons
https://imperavi.com/redactor/examples/buttons-default-icons/

**Comment by julianlam** [comment]
Hi @JonathanWatkins -- the source editing has been removed as it was easy to input incorrect html which would cause the NodeBB template to break. We've elected to keep it out until some sort of automatic html validator is implemented, but that is low priority for us.

If you want to use the source plugin, you can definitely modify the `redactor.core.js` file to add the plugin in 👍  Just keep in mind that future changes may conflict, so you will need to learn the git commands to resolve them.

**Comment by pitaj** [comment]
Could we add an admin setting to enable to HTML plugin?

**Comment by julianlam** [comment]
No objections to that 👍
