### ISSUE TITLE
Set the composer text direction rtl or ltr?

### ISSUE THREAD

**Issue by tuxado** [NodeBB/nodebb-plugin-composer-redactor#68]
Hi, How can i set the composer text direction on this plugin ?

It will be good to set it  directely from language setting of the nodebb

**Comment by tuxado** [comment]
resolved by hacking in redactor.core.js and plugins.json file by adding the translation and text direction

**Comment by julianlam** [comment]
Haven't had time to look into this but should be easy to determine from the rtl property on the html tag. Can you share your changes?

**Comment by tuxado** [comment]
hi,

These are the sources codes for the changes you can review thems

https://drive.google.com/file/d/0B4WEXAuiLIrVRUdrM3J0SGVkNWM/view?usp=sharing

composer.js

`var data = {
			title: title,
			mobile: composer.bsEnvironment === 'xs' || composer.bsEnvironment === 'sm',
			resizable: true,
			allowTopicsThumbnail: allowTopicsThumbnail,
			isTopicOrMain: isTopic || isMain,
			minimumTagLength: config.minimumTagLength,
			maximumTagLength: config.maximumTagLength,
			isTopic: isTopic,
			isEditing: isEditing,
			showHandleInput:  config.allowGuestHandles && (app.user.uid === 0 || (isEditing && isGuestPost && app.user.isAdmin)),
			handle: postData ? postData.handle || '' : undefined,
			formatting: composer.formatting,
			language: config.defaultLang.split("-")[0],
			tagWhitelist: ajaxify.data.tagWhitelist
		};`

redactor.core.js
`$(window).off('action:redactor.load');
		
		var options = {
		  lang: config.defaultLang.split("-")[0],
          imageUploadFields: {
            'cid': '#cmp-cid-' + data.post_uuid,
            '_csrf': config.csrf_token
          },
          fileUploadFields: {
            'cid': '#cmp-cid-' + data.post_uuid,
            '_csrf': config.csrf_token
          },
		  plugins: ['source', 'fontcolor', 'alignment', 'fontsize', 'textdirection']
        };
		
		options = $.extend({}, options, textarea.data());
		
        textarea.redactor(options);`

composer.tpl

`<textarea data-lang="{language}" data-direction="[[language:dir]]"></textarea>`



library.js

`
plugin.addScripts = function(scripts, callback) {
	
	scripts.push('/plugins/nodebb-plugin-composer-redactor/js/composer/languages/' + (meta.config.defaultLang || 'en-GB').split("-")[0] + '/composer-redactor.js');
	callback(null, scripts);
	
};`

preview

![preview](https://preview.ibb.co/k6vTnF/Sans_titre.png)

**Comment by julianlam** [comment]
v3.0.1
