### ISSUE TITLE
Problems with NodeBB 1.6.1 (Selection Straddles to end of Previous Line)

### ISSUE THREAD

**Issue by TroikaTronix** [NodeBB/nodebb-plugin-composer-redactor#69]
Hi There,
There are at least three bugs that are new for us since upgrading to NodeBB 1.6.1 a few days ago (We were several versions back with NodeBB previously.)

The details are in this NodeBB forum post.

https://community.nodebb.org/topic/11487/redactor-3-0-3-bugs-in-nodebb-1-6-1

Thanks for having a look.

Best Wishes,
Mark

**Comment by julianlam** [comment]
Unfortunately cannot repro (as detailed in reply to post)

**Comment by TroikaTronix** [comment]
Dear Julian,

I had to refine my repro for Bug 1, but after doing so, all three bugs were immediately reproducible on a fresh NodeBB site created at NodeBB.org. If you email me directly, I can give you the login info for that site. 

Mac OS Desktop: Safari = all three bugs happen
Mac OS Desktop: Google Chrome = bugs 1 + 2 happen

Furthermore, the same tests performed on a Redactor test page 

https://imperavi.com/redactor/examples/upload-images/

do not show the same bugs.

**Comment by julianlam** [comment]
Waiting on acquisition of latest Redactor code :smile:

**Comment by julianlam** [comment]
Just an update -- no movement on acquiring latest Redactor code... 🕐

**Comment by julianlam** [comment]
Closed via f7fac86c74eeba144fcdcd1f0f40f498de7408ed, v3.1.0

**Comment by julianlam** [comment]
@TroikaTronix Would appreciate giving v3.1.0 a test and reporting any regressions 😄

**Comment by julianlam** [comment]
_bump_

**Comment by TroikaTronix** [comment]
Hey there. I'm scrambling to release the new version of our software Isadora. I'll take a careful look as soon as I can.

**Comment by julianlam** [comment]
😄 Of course, take your time. 'tis was only a lighthearted bump. Have a good holiday break

**Comment by TroikaTronix** [comment]
We're getting the plugin installed on a testbed system on our server so we can find out more. I should be able to report to you in a few days.
