### ISSUE TITLE
autocomplete drop-down of @mention shown during composing

### ISSUE THREAD

**Issue by dongcai** [NodeBB/nodebb-plugin-composer-redactor#72]
When I start writing a reply with a mention, for example, @someone, then during my composing, the drop-down keeps on popping up even I don't use '@'. 
The screenshot attached..
<img width="429" alt="composer" src="https://user-images.githubusercontent.com/3952761/43912218-a503c636-9bcf-11e8-8204-bae4c8eefc67.png">

**Comment by yoyoyohamapi** [comment]
+1, same issue

**Comment by pig315** [comment]
+1 the same

**Comment by julianlam** [comment]
Seems this shows up only if the mention is at the beginning of the post, and only after you hit spacebar, is that correct?

**Comment by julianlam** [comment]
Please try latest `master` of NodeBB with composer-default v6.2.0
