### ISSUE TITLE
XSS Problem

### ISSUE THREAD

**Issue by yoyoyohamapi** [NodeBB/nodebb-plugin-composer-redactor#76]
Someone can insert following code through chrome dev tools

```html
<object data=data:text/html;base64,PHNjcmlwdD5hbGVydCgiS0NGIik8L3NjcmlwdD4=></object>
```

into the editor to do a xss attack.

![屏幕快照 2019-05-06 上午10 00 27](https://user-images.githubusercontent.com/8338436/57203925-8d94a100-6fe6-11e9-982c-111171de459e.png)

![image](https://user-images.githubusercontent.com/8338436/57203890-3bec1680-6fe6-11e9-8d2c-1cf046e1158e.png)

**Comment by julianlam** [comment]
Hi there,

Yes, chrome dev tools allows you to do a lot of things, including do things like this, but this doesn't count as a vulnerability as it requires the end user to do it to themselves via the dev tools.

**Comment by yoyoyohamapi** [comment]
I'm afraid you may misunderstand. I mean, I can **insert attack code into the editor** through dev tools，then I can post it to do a stored xss attacking. Anyone visit this topic would see the alert. @julianlam
