### ISSUE TITLE
Fileupload no longer possible since NodeBB 1.13.4

### ISSUE THREAD

**Issue by vhendin** [NodeBB/nodebb-plugin-composer-redactor#80]
I understand that you no longer support updates to this composer and I'm actively looking at supporting quill instead, but since [this commit](https://github.com/NodeBB/NodeBB/commit/6f504c4142d7584cdfe9347cd5cf183c655e2159), it is no longer possible to upload files.

The setting allowFileUploads has been removed and Redactor toolbar uses this setting to check if the button should be added, [here](https://github.com/NodeBB-Community/nodebb-plugin-composer-redactor/blob/ec318e4fc932aa97b8158f68a440417949eac5cf/static/lib/redactor.core.js#L177).

**Comment by julianlam** [comment]
This has now been resolved as of v3.5.0
