### ISSUE TITLE
Incompatibility with last version of nodebb 1.16.1

### ISSUE THREAD

**Issue by floufille** [NodeBB/nodebb-plugin-composer-redactor#81]
Configuration:

nodebb version: 1.16.1
nodebb-plugin-composer-default: 6.5.5 (deactivated)
nodebb-plugin-composer-redactor: 3.4.7 (activated)

Description:

When we want to write a new POST, the popup seems to be truncated
![image](https://user-images.githubusercontent.com/36710813/104131517-1563ae80-5377-11eb-8572-cb0dac2d9e15.png)

I've noticed, there is a javascript error: screenfull is not defined for file: composer.js

If i manually edit the javascript: ./node_modules/nodebb-plugin-composer-default/static/lib/composer.js on the server (+nodebb build)

Removing theses 2 sections: 

`		// Hide "zen mode" if fullscreen API is not enabled/available (ahem, iOS...)
		if (!screenfull.isEnabled) {
			$('[data-format="zen"]').addClass('hidden');
		}`

And : 
`	// Exit fullscreen
			if (screenfull.isEnabled && screenfull.isFullscreen) {
				screenfull.exit();
			}`

The plugin is working again.

**Comment by julianlam** [comment]
Thanks for reporting! :smile:
