### ISSUE TITLE
Markdown support

### ISSUE THREAD

**Issue by mrgame64** [NodeBB/nodebb-plugin-composer-redactor#9]
Currently when using Markdown in Redactor, it doesn't seem to be parsed by the Markdown plugin.

Would it be possible to support Markdown parsing alongside with HTML?

**Comment by julianlam** [comment]
@drewdotpro might know best, actually. Now that Redactor has its own server-side sanitisation, you could have the markdown plugin and redactor running at the same time...

**Comment by mrgame64** [comment]
They actually are both enabled, but I don't see any Markdown getting parsed

**Comment by drewdotpro** [comment]
Hmm, worth investigating. But I think it's important to remember that the aim of Redactor is a WYSIWYG. I'll leave this issue open as it's worth looking into.

**Comment by drewdotpro** [comment]
I don't think this can play. Essentially you'll get people who don't know what markdown is getting random formatting in their text they weren't expecting.

**Comment by psychobunny** [comment]
Just wanted to add that a few NodeBB plugins do use the parse.post hook and adds markdown-flavoured text. It's obviously not the fault of this composer but its a problem that needs looking into.

Ex: http://www.dutchstartuphub.com/topic/30/nederlandse-social-start-up-closing-the-loop-sluit-succesvol-eerste-investeringsronde-af

With nodebb-plugin-rss by @barisusakli
